"""Auto-populate smart_money/data/seeds.yaml from HL public leaderboard.

預設:抓活躍帳戶 × 多策略混合 → 寫入 seeds.yaml

用法:
    # 預設(用 DEFAULT_STRATEGY,約 80-100 地址)
    python -m smart_money.cli.seed

    # Dry-run 只印不寫
    python -m smart_money.cli.seed --dry-run

    # 自訂 N
    python -m smart_money.cli.seed --alltime-top 50 --month-top 50 \\
        --output smart_money/data/seeds.yaml

    # 用本機快取而非重下載(測試用)
    python -m smart_money.cli.seed --cache data/hl_leaderboard.json --use-cache

    # 單一策略(e.g. 只抓本月 ROI 前 100)
    python -m smart_money.cli.seed --only month:roi:100
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import yaml

from smart_money.scanner.leaderboard import (
    DEFAULT_STRATEGY,
    SeedBucket,
    build_seed_set,
    fetch_leaderboard,
    filter_active,
)

logger = logging.getLogger(__name__)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m smart_money.cli.seed",
        description="Auto-build seed wallets from HL public leaderboard.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("smart_money/data/seeds.yaml"),
        help="Output yaml path (default: smart_money/data/seeds.yaml).",
    )
    parser.add_argument(
        "--cache",
        type=Path,
        default=Path("data/hl_leaderboard.json"),
        help="Path to cache the ~28MB leaderboard JSON (gitignored).",
    )
    parser.add_argument(
        "--use-cache",
        action="store_true",
        help="Read leaderboard from cache instead of network (fast iteration).",
    )
    parser.add_argument(
        "--min-account-value",
        type=float,
        default=10_000.0,
        help="Discard accounts below this USD value (default: 10000).",
    )
    parser.add_argument(
        "--min-month-volume",
        type=float,
        default=100_000.0,
        help="Discard accounts with 30-day volume below this (default: 100000).",
    )
    parser.add_argument(
        "--only",
        action="append",
        metavar="WINDOW:METRIC:N",
        help=("Custom bucket(s), e.g. 'month:roi:50 week:pnl:20'. "
              "Overrides default strategy. Can be repeated."),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print resulting addresses, don't write the yaml.",
    )
    parser.add_argument(
        "--merge",
        action="store_true",
        help="Merge with existing seeds.yaml instead of overwriting.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
    )
    return parser


def _parse_only(spec_list: list[str]) -> tuple[SeedBucket, ...]:
    buckets: list[SeedBucket] = []
    for spec in spec_list:
        try:
            window, metric, n_str = spec.split(":")
            n = int(n_str)
        except ValueError as exc:
            raise SystemExit(f"bad --only spec {spec!r} (want WINDOW:METRIC:N)") from exc
        if window not in ("day", "week", "month", "allTime"):
            raise SystemExit(f"bad window {window!r} in {spec}")
        if metric not in ("pnl", "roi", "volume"):
            raise SystemExit(f"bad metric {metric!r} in {spec}")
        buckets.append(SeedBucket(window=window, metric=metric,  # type: ignore[arg-type]
                                    n=n, label=f"{window}_{metric}_top"))
    return tuple(buckets)


def _load_existing(path: Path) -> list[str]:
    """Read current seeds.yaml to find addresses already present."""
    if not path.exists():
        return []
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError:
        return []
    existing: list[str] = []
    for item in data.get("wallets") or []:
        if isinstance(item, str):
            existing.append(item.lower())
        elif isinstance(item, dict) and item.get("address"):
            existing.append(str(item["address"]).lower())
    return existing


def _write_yaml(path: Path, entries: list[tuple[str, list[str], dict]]) -> None:
    """Write seeds.yaml with metadata for each wallet."""
    wallets_block = []
    for addr, tags, meta in entries:
        wallets_block.append({
            "address": addr,
            "tags": tags,
            **meta,
        })
    out = {"wallets": wallets_block}
    path.parent.mkdir(parents=True, exist_ok=True)
    # preserve the header comment by writing manually
    header = (
        "# Auto-generated by `python -m smart_money.cli.seed`\n"
        "# You can re-run any time; --merge keeps existing entries.\n"
        "# Each wallet has tags showing which HL leaderboard strategy picked it.\n"
        "#\n"
    )
    body = yaml.safe_dump(out, sort_keys=False, allow_unicode=True)
    path.write_text(header + body)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    logging.basicConfig(
        level=args.log_level,
        format="%(asctime)s %(levelname)s %(name)s - %(message)s",
    )

    strategy = _parse_only(args.only) if args.only else DEFAULT_STRATEGY
    logger.info("Strategy buckets:")
    for b in strategy:
        logger.info("  %s:%s top %d → tag=%s", b.window, b.metric, b.n, b.label)

    rows = fetch_leaderboard(cache_path=args.cache, use_cache=args.use_cache)

    active = filter_active(
        rows,
        min_account_value=args.min_account_value,
        min_month_volume=args.min_month_volume,
    )
    logger.info("After active-filter: %d / %d kept (min_acct=$%.0f, min_vol=$%.0f)",
                len(active), len(rows), args.min_account_value, args.min_month_volume)

    seeds = build_seed_set(active, strategy=strategy)
    logger.info("Deduplicated seed set: %d unique addresses", len(seeds))

    # Preview top 10
    logger.info("Top 10 by bucket-hits:")
    for row, tags in seeds[:10]:
        logger.info("  %s hits=%d  acct=$%.0fk  mo_pnl=$%.0f  mo_roi=%.1f%%  tags=%s",
                    row.address, len(tags), row.account_value / 1000,
                    row.get("month", "pnl"), row.get("month", "roi") * 100,
                    tags)

    if args.merge:
        existing = set(_load_existing(args.output))
        seeds = [(row, tags) for (row, tags) in seeds if row.address not in existing]
        logger.info("Merge mode: %d new addresses after removing %d existing",
                    len(seeds), len(existing))

    if args.dry_run:
        print(f"\n=== Dry-run: {len(seeds)} addresses would be written to {args.output} ===")
        for row, tags in seeds:
            print(f"  {row.address}  [{', '.join(tags)}]")
        return 0

    # Prepare entries
    entries = [
        (row.address, tags, {
            "account_value_usd": round(row.account_value, 0),
            "month_pnl_usd": round(row.get("month", "pnl"), 0),
            "month_roi_pct": round(row.get("month", "roi") * 100, 2),
            "alltime_pnl_usd": round(row.get("allTime", "pnl"), 0),
        })
        for row, tags in seeds
    ]

    if args.merge:
        # Read + keep existing, append new
        existing_data = {}
        try:
            existing_data = yaml.safe_load(args.output.read_text()) or {}
        except Exception:       # noqa: BLE001
            pass
        existing_wallets = existing_data.get("wallets") or []
        # normalise existing entries to dict form
        existing_norm: list[dict] = []
        for item in existing_wallets:
            if isinstance(item, str):
                existing_norm.append({"address": item})
            elif isinstance(item, dict):
                existing_norm.append(item)
        new_block = existing_norm + [
            {"address": addr, "tags": tags, **meta}
            for addr, tags, meta in entries
        ]
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(yaml.safe_dump({"wallets": new_block}, sort_keys=False))
    else:
        _write_yaml(args.output, entries)

    logger.info("✓ Wrote %d seeds → %s", len(entries), args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
